### ISSUE TITLE
Not an anti-pattern anymore?

### ISSUE THREAD

**Issue by blicksky** [mearns/extrinsic-promises#27]
The functionality provided by this library is now standard in ES2024 by way of [Promise.withResolvers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers).

**Comment by mearns** [comment]
Nice, thanks @blicksky ! I've updated the README with information on migrating to `withResolvers`, and deprecated the package on npm (which is good, because the dependencies are too far out of date to want to mess with updating :D)
