### ISSUE TITLE
Address npm audit issues

### ISSUE THREAD

**Issue by mearns** [mearns/extrinsic-promises#9]
If you run `npm audit` from the repo, you'll get a bunch of warnings. We need someone to go through and fix these. If you're looking for a way to contribute to this package, the npm ecosystem, or open source software in general, you can fork this repo, address as many or as few of these audit issues as you want, and submit a pull request =)

**Comment by blicksky** [comment]
Have you considered enabling https://help.github.com/en/articles/configuring-automated-security-fixes?
